global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métricas do OTEL Collector
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  
  # Métricas do Prometheus (self-monitoring)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
